#+title: simulacrum.el
Define custom input event types for the Emacs command loop.

Emacs input events are limited to keys, mouse actions, and a few
special types.  Simulacrum extends this by letting you define custom
event types that carry arbitrary data.  This is useful when an
external process (e.g., a voice control engine) needs to invoke
commands with structured arguments through the command loop.

* Installation
This package is available on [[https://melpa.org/#/getting-started][MELPA]] as ~simulacrum~.

* Usage
Define an event type, bind it to a command, then generate events:

#+begin_src elisp
  (simulacrum-define-event-type my-event)

  (keymap-global-set "<my-event>"
                     (simulacrum-command
                      (lambda (n) (message "Got %s" n))))

  ;; Later, e.g. from an external process:
  (simulacrum-generate-event 'my-event 42)
#+end_src

When the command loop handles the generated event, it will execute the
command and print "Got 42".

For an example of usage from another package, see [[https://github.com/ErikPrantare/phony.el][phony.el]].

* Versioning system
:PROPERTIES:
:CUSTOM_ID: versioning-system
:END:
This project uses [[https://semver.org/][semantic versioning]].  While still on 0.y.z, an
increment of y signals breaking changes.
